development:
  domain_database:
    adapter: postgresql
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    schema_search_path: public
    encoding: utf8
    template: template0
    pool: 10 
    timeout: 5000
    database: team_builder_domain_development
  drb_server:
    scheme: druby
    host: 127.0.0.1
    port: 8787
  event_connection:
    scheme: amqp
    host: 127.0.0.1
    port: 5672
  event_exchange: team-builder-events

test:
  domain_database:
    adapter: sqlite3
    pool: 5
    timeout: 5000
    database: db/test_domain.sqlite3
  event_connection:
    scheme: amqp
    host: 127.0.0.1
    port: 5672
  event_exchange: events

production:
  domain_database:
    adapter: sqlite3
    pool: 5
    timeout: 5000
    database: db/production_domain.sqlite3
  drb_server:
    protocol: druby
    host: 127.0.0.1
    port: 8787
  event_connection:
    scheme: amqp
    userinfo: amqp:password
    host: 127.0.0.1
    port: 9797
  event_exchange: events
